### ISSUE TITLE
[Feature]: Crawler

### ISSUE THREAD

**Issue by bams11** [AICP-UNIST/news-crawler#3]
### What
* News Article

### Where
* Naver News

### How
* Python Crawling Library with Chat GPT

### To-do
* Sample Code with Class

member

- [x] period
- [x] max article number
- [x] title, link
- [x] result (mapped with title)

method

- [x] get article name and link
- [x] crawling with title or link
- [x] result to csv

### Motivation

Before conducting the AICP main experiment, we will make a crawler for a simple Toy project.
